import {
  brainstem, brainstem1, brainstem2, brainstem3, brainstem4, brainstem5, brainstem6,
  hostage, hostage1, hostage2, hostage3, hostage4, hostage5, hostage6, hostage7, hostage8, hostage9, hostage10, hostage11,
  shapeshooter, shapeshooter1, shapeshooter2, shapeshooter3, shapeshooter4, shapeshooter5, shapeshooter6, shapeshooter7,
  ue5level, ue5level1, ue5level2, ue5level3, ue5level4, ue5level5, ue5level6, ue5level7, ue5level8, ue5level9, ue5level10, ue5level11, ue5level12, ue5level13, ue5level14, ue5level15, ue5level16, ue5level17,
  stenovate
} from "../assets";

const projects = [
  {
    id: "brainstem",
    name: "Brainstem (prototype)",
    description:
      "<i>Brainstem</i> is a 2D side-scrolling action-adventure platformer created in Godot 4.2 using the GDScript programming language. The game combines original assets, including a custom-composed soundtrack for level two, with meticulously tailored graphics and audio sourced from Twitch.io and Pixabay.com, ensuring a cohesive and immersive player experience. Built to showcase fluid mechanics and dynamic environments, <i>Brainstem</i> reflects a strong foundation in game design, asset integration, and gameplay refinement.",
    tags: [
      { name: "godot", color: "blue-text-gradient" },
      { name: "aseprite", color: "green-text-gradient" },
      { name: "photoshop", color: "pink-text-gradient" },
      { name: "cakewalk", color: "orange-text-gradient" },
      { name: "audacity", color: "purple-text-gradient" },
    ],
    image: brainstem,
    image1: brainstem1,
    image2: brainstem2,
    image3: brainstem3,
    image4: brainstem4,
    image5: brainstem5,
    image6: brainstem6,
    video: "https://www.youtube.com/embed/dch-rlHtmAg?si=akbYlHMwsKHOUw_t",
    video_title: "Brainstem Gameplay Demo",
    source_code_link: "https://github.com/snl60/Brainstem",
  },
  {
    id: "hostage",
    name: "Hostage Negotiation",
    description:
      "A custom single-player level in Unreal Engine 5, showcasing my skill in integrating environment design with engaging, combat-focused gameplay. Using Unreal's Landscape and Foliage systems, I developed a visually immersive terrain. The Blueprint system enabled fluid player interactions and combat mechanics, while custom enemy AI—built with Behavior Trees and Blackboards—provides challenging, adaptive gameplay. This project highlights my skill in uniting design elements and technical systems to create a seamless, interactive experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
      { name: "mixamo", color: "green-text-gradient" },
      { name: "blender", color: "pink-text-gradient" },
    ],
    image: hostage,
    image1: hostage1,
    image2: hostage2,
    image3: hostage3,
    image4: hostage4,
    image5: hostage5,
    image6: hostage6,
    image7: hostage7,
    image8: hostage8,
    image9: hostage9,
    image10: hostage10,
    image11: hostage11,
    source_code_link: "None",
  },
  {
    id: "shape-shooter",
    name: "Shape Shooter",
    description:
      "Shape Shooter is a fast-paced top-down shooting game where players control a cone that fires projectiles to fend off waves of enemy shapes. Each enemy type has unique behaviors, creating dynamic challenges as players advance through increasingly intense waves. With responsive controls and strategic gameplay, Shape Shooter combines simplicity with depth for an engaging, action-packed experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
      { name: "c++", color: "green-text-gradient" },
      { name: "visual studio", color: "pink-text-gradient" },
    ],
    image: shapeshooter,
    image1: shapeshooter1,
    image2: shapeshooter2,
    image3: shapeshooter3,
    image4: shapeshooter4,
    image5: shapeshooter5,
    image6: shapeshooter6,
    image7: shapeshooter7,
    source_code_link: "https://github.com/snl60/ShapeShooter",
  },
  {
    id: "ue5level",
    name: "Unreal Engine 5 Level",
    description:
      "This Unreal Engine 5 level highlights my skills in environment design, using Landscape and Foliage tools for immersive terrain and Blueprint systems for gameplay. Players engage with enemy bear AI, unlock doors by leveling up, and reach a win state by stepping on a pressure plate. The level includes custom UI elements like a HUD, pause, and main menus, along with audio cues, particle effects, and a cinematic flythrough at the start. This project demonstrates my ability to integrate design, gameplay, and UI for a cohesive, interactive experience.",
    tags: [
      { name: "unreal engine", color: "blue-text-gradient" },
    ],
    image: ue5level,
    image1: ue5level1,
    image2: ue5level2,
    image3: ue5level3,
    image4: ue5level4,
    image5: ue5level5,
    image6: ue5level6,
    image7: ue5level7,
    image8: ue5level8,
    image9: ue5level9,
    image10: ue5level10,
    image11: ue5level11,
    image12: ue5level12,
    image13: ue5level13,
    image14: ue5level14,
    image15: ue5level15,
    image16: ue5level16,
    image17: ue5level17,
    source_code_link: "None",
  },
  {
    id: "stenovate",
    name: "Stenovate Speech-to-Text",
    description:
      "Stenovate is an open-source speech-to-text application designed for fast, accurate transcription across multiple languages. Built on OpenAI's powerful Whisper model, Stenovate enables users to convert audio files into text with exceptional precision, ideal for professionals and multilingual environments. With a user-friendly interface, users can easily select audio files for transcription, customize save locations, and manage transcriptions seamlessly. Stenovate also includes custom file management and user-defined save directories, making it a reliable, versatile tool for accurate speech transcription in various workflows.",
    tags: [
      { name: "python", color: "blue-text-gradient" },
      { name: "openai whisper", color: "green-text-gradient" },
      { name: "tkinter", color: "pink-text-gradient" },
      { name: "pytorch", color: "orange-text-gradient" },
      { name: "open source", color: "purple-text-gradient" },
    ],
    image: stenovate,
    video: "https://www.youtube.com/embed/BTlptlhtD-8?si=FK8xQxG5mmZN4Yxc",
    video_title: "Stenovate: Powerful Open-Source Speech-to-Text App for Accurate Transcription",
    source_code_link: "https://github.com/snl60/stenovate",
  },
];

export default projects;
